/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayRouteImport } from './routes/pay'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayRedirectSuccessRouteImport } from './routes/pay.redirect.success'
import { Route as PayRedirectCancelRouteImport } from './routes/pay.redirect.cancel'
import { Route as DemoRedirectSuccessRouteImport } from './routes/demo.redirect.success'
import { Route as DemoRedirectCancelRouteImport } from './routes/demo.redirect.cancel'

const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRedirectSuccessRoute = PayRedirectSuccessRouteImport.update({
  id: '/redirect/success',
  path: '/redirect/success',
  getParentRoute: () => PayRoute,
} as any)
const PayRedirectCancelRoute = PayRedirectCancelRouteImport.update({
  id: '/redirect/cancel',
  path: '/redirect/cancel',
  getParentRoute: () => PayRoute,
} as any)
const DemoRedirectSuccessRoute = DemoRedirectSuccessRouteImport.update({
  id: '/redirect/success',
  path: '/redirect/success',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRedirectCancelRoute = DemoRedirectCancelRouteImport.update({
  id: '/redirect/cancel',
  path: '/redirect/cancel',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/pay': typeof PayRouteWithChildren
  '/demo/redirect/cancel': typeof DemoRedirectCancelRoute
  '/demo/redirect/success': typeof DemoRedirectSuccessRoute
  '/pay/redirect/cancel': typeof PayRedirectCancelRoute
  '/pay/redirect/success': typeof PayRedirectSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/pay': typeof PayRouteWithChildren
  '/demo/redirect/cancel': typeof DemoRedirectCancelRoute
  '/demo/redirect/success': typeof DemoRedirectSuccessRoute
  '/pay/redirect/cancel': typeof PayRedirectCancelRoute
  '/pay/redirect/success': typeof PayRedirectSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/pay': typeof PayRouteWithChildren
  '/demo/redirect/cancel': typeof DemoRedirectCancelRoute
  '/demo/redirect/success': typeof DemoRedirectSuccessRoute
  '/pay/redirect/cancel': typeof PayRedirectCancelRoute
  '/pay/redirect/success': typeof PayRedirectSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/pay'
    | '/demo/redirect/cancel'
    | '/demo/redirect/success'
    | '/pay/redirect/cancel'
    | '/pay/redirect/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/pay'
    | '/demo/redirect/cancel'
    | '/demo/redirect/success'
    | '/pay/redirect/cancel'
    | '/pay/redirect/success'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/pay'
    | '/demo/redirect/cancel'
    | '/demo/redirect/success'
    | '/pay/redirect/cancel'
    | '/pay/redirect/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  PayRoute: typeof PayRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/redirect/success': {
      id: '/pay/redirect/success'
      path: '/redirect/success'
      fullPath: '/pay/redirect/success'
      preLoaderRoute: typeof PayRedirectSuccessRouteImport
      parentRoute: typeof PayRoute
    }
    '/pay/redirect/cancel': {
      id: '/pay/redirect/cancel'
      path: '/redirect/cancel'
      fullPath: '/pay/redirect/cancel'
      preLoaderRoute: typeof PayRedirectCancelRouteImport
      parentRoute: typeof PayRoute
    }
    '/demo/redirect/success': {
      id: '/demo/redirect/success'
      path: '/redirect/success'
      fullPath: '/demo/redirect/success'
      preLoaderRoute: typeof DemoRedirectSuccessRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/redirect/cancel': {
      id: '/demo/redirect/cancel'
      path: '/redirect/cancel'
      fullPath: '/demo/redirect/cancel'
      preLoaderRoute: typeof DemoRedirectCancelRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoRedirectCancelRoute: typeof DemoRedirectCancelRoute
  DemoRedirectSuccessRoute: typeof DemoRedirectSuccessRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoRedirectCancelRoute: DemoRedirectCancelRoute,
  DemoRedirectSuccessRoute: DemoRedirectSuccessRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface PayRouteChildren {
  PayRedirectCancelRoute: typeof PayRedirectCancelRoute
  PayRedirectSuccessRoute: typeof PayRedirectSuccessRoute
}

const PayRouteChildren: PayRouteChildren = {
  PayRedirectCancelRoute: PayRedirectCancelRoute,
  PayRedirectSuccessRoute: PayRedirectSuccessRoute,
}

const PayRouteWithChildren = PayRoute._addFileChildren(PayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  PayRoute: PayRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
